# Use official Node.js base image
FROM node:18
# Set the working directore
WORKDIR /usr/src/app
# COPY package.json ./
# Install dependies
RUN npm install
# Copy application code
COPY..
# Expose the port
EXPOSE 3000
# Start the app port 
CMD ["node , ""patient-service.js"]
